schema-create:
  prefix: 'schema:create'
  class: PegaseORM\Command\SchemaCommands
  method: create

schema:drop:
  prefix: 'schema:drop'
  class: PegaseORM\Command\SchemaCommands
  method: drop

schema:truncate:
  prefix: 'schema:truncate'
  class: PegaseORM\Command\SchemaCommands
  method: drop

